# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [released, edited]
  push:
    branches: [master]

jobs:
  build:
    uses: './.github/workflows/build-check.yml'

  publish-npm:
    if: >-
      ${{ github.event == 'release'
        && (github.event.release.action == 'released'
          || (!github.event.release.release.draft
          && !github.event.release.release.prerelease)) }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm publish
